//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceGeneration
    {
        public ResourceGeneration()
        {
            this.ResourceCopies = new HashSet<ResourceCopy>();
        }
    
        public int GenerationId { get; set; }
        public int ResourceId { get; set; }
        public System.DateTime GenerationDate { get; set; }
        public int GenerationCopyCount { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<ResourceCopy> ResourceCopies { get; set; }
        public virtual ResourceSetup ResourceSetup { get; set; }
    }
}
